# Generated by Django 5.2.4 on 2025-08-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('market_open', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
